package com.rameshta.photocompressor.ui.theme

import androidx.compose.ui.graphics.Color

val BrandPrimaryLight = Color(0xFF006D77)
val BrandOnPrimaryLight = Color(0xFFFFFFFF)
val BrandPrimaryContainerLight = Color(0xFFBFEFF1)
val BrandOnPrimaryContainerLight = Color(0xFF00363B)
val BrandSecondaryLight = Color(0xFF6E5B00)
val BrandOnSecondaryLight = Color(0xFFFFFFFF)
val BrandSecondaryContainerLight = Color(0xFFFFE68A)
val BrandOnSecondaryContainerLight = Color(0xFF241A00)
val BrandBackgroundLight = Color(0xFFF7FAF9)
val BrandOnBackgroundLight = Color(0xFF171D1D)
val BrandSurfaceLight = Color(0xFFFBFDFB)
val BrandOnSurfaceLight = Color(0xFF171D1D)
val BrandSurfaceVariantLight = Color(0xFFDDE7E6)
val BrandOnSurfaceVariantLight = Color(0xFF3F4948)
val BrandOutlineLight = Color(0xFF6F7978)
val BrandOutlineVariantLight = Color(0xFFC0C9C8)
val BrandErrorLight = Color(0xFFBA1A1A)
val BrandOnErrorLight = Color(0xFFFFFFFF)

val BrandPrimaryDark = Color(0xFF73D7DF)
val BrandOnPrimaryDark = Color(0xFF00363B)
val BrandPrimaryContainerDark = Color(0xFF004F57)
val BrandOnPrimaryContainerDark = Color(0xFFBFEFF1)
val BrandSecondaryDark = Color(0xFFE5C84B)
val BrandOnSecondaryDark = Color(0xFF3A3000)
val BrandSecondaryContainerDark = Color(0xFF534600)
val BrandOnSecondaryContainerDark = Color(0xFFFFE68A)
val BrandBackgroundDark = Color(0xFF101414)
val BrandOnBackgroundDark = Color(0xFFE0E4E3)
val BrandSurfaceDark = Color(0xFF121818)
val BrandOnSurfaceDark = Color(0xFFE0E4E3)
val BrandSurfaceVariantDark = Color(0xFF3F4948)
val BrandOnSurfaceVariantDark = Color(0xFFC0C9C8)
val BrandOutlineDark = Color(0xFF899392)
val BrandOutlineVariantDark = Color(0xFF3F4948)
val BrandErrorDark = Color(0xFFFFB4AB)
val BrandOnErrorDark = Color(0xFF690005)
